### ISSUE TITLE
Config merge conflict for field generatedID

### ISSUE THREAD

**Issue by BeatlesBOB** [BjornTheProgrammer/codemirror-collab-react-codemirror#3]
Hi, I've tried to implement your solution on top of Sandpack-react, but when I firstly launch the application I get the following error :
_Config merge conflict for field generatedID_
did your have already encountered this ?

are you available to help me on the solution ?

**Comment by BjornTheProgrammer** [comment]
Hello, can you describe the steps to reproduce this issue in more detail. Also, try deleting and recloning the entire repository and see if that helps. Also describe which branch you are having this issue for.

**Comment by BeatlesBOB** [comment]
Hello, thank's you very much for your reply, I'm on the Multi-doc branch but seems to do it on the master too.
It's maybe because of Sandpack that the issue appear. It's like Codemirror/Collab generate an ID but when it merge the ID doesn't  correspond.  There is no step to reproduce on your base code. I was wondering if you can help us on mine as you seems to understand way better codemirror and it's feature.

**Comment by BjornTheProgrammer** [comment]
Feel free to send the repository, I'd be happy to view it, and attempt to debug it.

**Comment by BeatlesBOB** [comment]
Thank's you very much I really appreciate it :
https://github.com/Maquequette/front
Here is the repo, the Code Editor is on /dev

**Comment by BeatlesBOB** [comment]
Hi @BjornTheProgrammer, hope You are doing well. Did you get time to see the issue ?
I'm still strunggling on the same kind of issue.

**Comment by BjornTheProgrammer** [comment]
Hello @BeatlesBOB,

I apologize for not responding sooner, I didn't see this message till now. Do you mind telling me how to replicate the issue step by step for your repo? Additionally, it seems like it would be extremely hard to debug this application without setting up the backend completely. I don't have the will to set up an AWS project, a database, and use my GitHub key to get the backend up and running. Instead, could you provide me an API endpoint to connect to for the dev branch for testing?
